name: wake-typecheck

on:
  push:
    path-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  typecheck:
    name: 'Wake typecheck'
    runs-on: ubuntu-latest

    steps:
    - uses: sifive/wit/actions/init@v0.13.2
    - uses: sifive/environment-blockci-sifive/actions/wake@0.7.1
